### ISSUE TITLE
Adopt layout from https://github.com/fulldecent/swift5-module-template

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/FDTake#117]
A modern project layout for Swift modules is defined at https://github.com/fulldecent/swift5-module-template

# Work plan

- [ ] Study best practices at link above
- [ ] Apply the "Recipe" from the Swift 5 Module Template to this project
  - Organization: William Entriken
  - Author: William Entriken
  - Domain: net.phor
  - Date: today's date
- [ ] Ensure that PR does not change the current development team

For an example of a project that successfully adopted the modern project layout, see https://github.com/fulldecent/FDChessboardView and FDBarGauge

# Follow-on work

- [ ] Make a minor version feature release with this updated project

**Comment by yaroslav-zhurakovskiy** [comment]
According to this https://bugs.swift.org/browse/SR-2866 SPM does currently support resources. We can't include "Localizable.strings" and any other assets into a swift package.

See also https://stackoverflow.com/questions/39815054/how-to-include-assets-resources-in-a-swift-package-manager-library

**Comment by fulldecent** [comment]
Good point.

Let's do this:

- [ ] Remove localization from FDTake and hard code in these strings:
   * "cancel" = "🛑";
   * "chooseFromLibrary" = "📕";
   * "chooseFromPhotoRoll" = "📒";
   * "noSources" = "📵";
   * "takePhoto" = "📷";
   * "takeVideo" = "🎥";
- [ ] Move the assets to the iOS example app and use FDTake string overrides to implement localization
- [ ] In the readme explain how people can implement the iOS example app localized strings files into their own app

End result is that it works with Swift Package Manager and localization works but requires a couple of steps.

**Comment by fulldecent** [comment]
Fixed in c3450d12a3aaa2325465935c2efad156d76672de
